name: DocGen

on: 
  pull_request:
    paths:
      - "**/variables.tf"
      - "**/outputs.tf"

jobs:
  docgen:
    name: DocGen
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v1
      - name: Build new docs
        run: make docs
      - name: Push docs to PR
        run: make push-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
